### ISSUE TITLE
Typo  error

### ISSUE THREAD

**Issue by i39** [DanieleDeSensi/peafowl#28]
I think what is the typo  here:
https://github.com/DanieleDeSensi/peafowl/blob/4c479febc25cf319398468eae6b699c6c40c0cad/src/inspectors/sip.c#L1124

Should be (*(tmp + 1) == '**I**' || *(tmp + 1) == 'i') &&

**Comment by DanieleDeSensi** [comment]
Hi, 
I think you are right, thank you for the notification.
Could you open a PR?

Thank you.
Daniele

**Comment by i39** [comment]
Yes. I'll do it :)

**Comment by DanieleDeSensi** [comment]
Fixed in #29
