### ISSUE TITLE
DPDK Example

### ISSUE THREAD

**Issue by mmanoj** [DanieleDeSensi/peafowl#33]
Hi,
Can you provide any working example with DPDK and classify traffic using peafowl.

Thank you,
Manoj

**Comment by DanieleDeSensi** [comment]
Hi Manoj,
I'm not very familiar with DPDK. However, Peafowl works with any packet capture technology. It is enough to provide to Peafowl the pointer to the packet (either to Ethernet, IP, or TCP/UDP header). You can probably easily adapt one of the DPDK examples in the tutorial. If you manage to do so, could you open a PR? 

Best,
Daniele

**Comment by mmanoj** [comment]
Hi Daniele,

Thanks, I will check and update you. Can you provide the below details to get a better understand of the future scope of the project?

1.High-level comparison with nDPI and what are advantages over nDPI?
2. Roadmap and features going to implement in peafowl.

So, we can make the project to the next level together.

**Comment by DanieleDeSensi** [comment]
Hi Manoj,
1. nDPI is a more complete product compare to Peafowl. It has a larger community and a larger development team, and its development (the OpenDPI one) started many years before Peafowl development. At the same time, nDPI is probably more monolithic, and last time I checked it didn't provide some features like protocol fields extraction, custom packet tagging, etc (I don't know what the nDPI status now).
2. About the roadmap and features, I would like support more protocols and to re-introduce the support for multicore architectures.

Drop me an email if you want to tell me more about your use cases, etc...

**Comment by mmanoj** [comment]
Hi Daniele,

Thanks for the quick update and details. Sure, I will send the email and will discuss the more detailed roadmap and action plan.

**Comment by DanieleDeSensi** [comment]
Closed for inactivity
