### ISSUE TITLE
Packet check with Libtins

### ISSUE THREAD

**Issue by Tomasz158** [DanieleDeSensi/peafowl#34]
Can you, please, give an example how can I get a packet from live capture with pcap and classify it? For example:
`if(packet.protocol == IP_ICMP){
dosomething();
}`

I would like to use the peaflow.c / peaflow.h functions and not use js

**Comment by DanieleDeSensi** [comment]
The question is not clear. Do you want to use it with libtins or with pcap? If you want to use it with libtins, you should check libtins documentation to understand how to get a pointer to the IP layer data.

**Comment by DanieleDeSensi** [comment]
Closed for inactivity.
