### ISSUE TITLE
TCP reusing port

### ISSUE THREAD

**Issue by max197616** [DanieleDeSensi/Peafowl#5]
Library had some problems when received tcp packet with new syn flag (new session) on already established session. In this case dpi thinks that protocol already detected. I think needed some code to handle this situation.

**Comment by DanieleDeSensi** [comment]
Could you please provide me a .pcap file to reproduce this scenario?
Thanks.

**Comment by max197616** [comment]
I sent pcap file to your email. I don't want to publish it at the public.
Thanks.

**Comment by DanieleDeSensi** [comment]
I fixed the bug in the last commit.
Thank you.
